//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTweetBooty
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TweetBotDBEntities : DbContext
    {
        public TweetBotDBEntities()
            : base("name=TweetBotDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BannedWord> BannedWords { get; set; }
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<Hashtag> Hashtags { get; set; }
        public virtual DbSet<Link> Links { get; set; }
        public virtual DbSet<Tweeted> Tweeteds { get; set; }
        public virtual DbSet<Tweet> Tweets { get; set; }
        public virtual DbSet<SearchTerm> SearchTerms { get; set; }
    }
}
